max_num: 100
data_type: succ # init or grasp or succ or init_template or new_template
check_success:    # True or False or None

hand:
  mode: visual  # visual or collision
  init_body: False
  contact: False
  skeleton: False

object:
  contact: False

cust_log_dir: ${log_dir}