one_for_each_obj: False
data_type: "grasp" # "init" or "grasp" or "template"
check_succ: True

vis_hand_contact: False
vis_hand_sk: False

hand_init_mesh: False
hand_mesh: True
hand_contact: True

vis_obj_mesh: True
vis_obj_contact: False
cust_log_dir: ${log_dir}